nostr:
  enabled: true
  relay_url: "wss://groups.0xchat.com"
  kinds: [9]
  subscription_id: "dvm_sub"
  run_seconds: 30
  additional_filters:
    tags:
      h: "825f1ed57f20d06d43e93f3cb8207d61ce8cdfff9d9f6722540329c00fba1b44"
      # You can add more tag filters here, e.g.:
      # foo: "bar"

summarizer:
  type: "openai"
  openai_api_key: "YOUR_OPENAI_API_KEY"

chroma_persist_directory: ".chroma"
collection_name: "nostr_events"
embed_model_name: "all-MiniLM-L6-v2"
batch_size: 64