chroma:
  model: "all-MiniLM-L6-v2"

summarizer:
  model: "gpt-4o-mini"

nostr:
  relay: "wss://groups.0xchat.com"
  filter:
    "kinds": [9]
    "#h": "825f1ed57f20d06d43e93f3cb8207d61ce8cdfff9d9f6722540329c00fba1b44"
